//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStandart {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeStandart.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одно объявление должно содержать не более одного поля..
        /// </summary>
        public static string CREO001_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO001_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятно, объявление  содержит более одного поля..
        /// </summary>
        public static string CREO001_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO001_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделить объявления для всех полей..
        /// </summary>
        public static string CREO001_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO001_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одно объявление должно содержать не более одной переменной..
        /// </summary>
        public static string CREO002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO002_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятно, объявление  содержит более одной переменной..
        /// </summary>
        public static string CREO002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделить объявления всех переменных.
        /// </summary>
        public static string CREO002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO002_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявление атрибута должно быть на отдельной строке..
        /// </summary>
        public static string CREO003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO003_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует символ перевода строки после использования атрибута.
        /// </summary>
        public static string CREO003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести атрибут в отдельную строку.
        /// </summary>
        public static string CREO003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO003_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед управляющими операторами должны быть пустая строка.
        /// </summary>
        public static string CREO004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO004_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор типа &apos;{0}&apos; не разделён пустой строкой с предыдущим кодом.
        /// </summary>
        public static string CREO004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед управляющими операторами должна быть пустая строка.
        /// </summary>
        public static string CREO004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO004_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Между блоком using и остальным кодом должны быть пустая строка.
        /// </summary>
        public static string CREO005_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO005_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо вставить пустую строку после  &apos;{0}&apos;.
        /// </summary>
        public static string CREO005_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO005_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет пустой строки после блока using.
        /// </summary>
        public static string CREO005_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO005_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каждый элемент перечисления должен быть записан в PascalCase.
        /// </summary>
        public static string CREO006_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO006_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элемент {0} перечисления &apos;{1}&apos; записан не в PascalCase.
        /// </summary>
        public static string CREO006_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO006_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элемент перечисления записан не в PascalCase.
        /// </summary>
        public static string CREO006_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO006_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя производить явное сравнение с true или false.
        /// </summary>
        public static string CREO007_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO007_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выражение &apos;{0}&apos; содержит явное сравнение с &apos;{1}&apos;.
        /// </summary>
        public static string CREO007_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO007_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержится явное сравнение с булевым литералом.
        /// </summary>
        public static string CREO007_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO007_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начале идентификатора интерфейса следует избегать повторения символа &apos;I&apos;.
        /// </summary>
        public static string CREO008_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO008_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор интерфейса &apos;{0}&apos; содержит в начале повторение символа &apos;I&apos;.
        /// </summary>
        public static string CREO008_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO008_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор интерфейса содержит повторение символа &apos;I&apos;.
        /// </summary>
        public static string CREO008_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO008_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификаторы булевых переменных должны иметь один из следующих префиксов: &apos;is&apos;, &apos;has&apos;, &apos;can&apos;, &apos;do&apos;.
        /// </summary>
        public static string CREO009_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO009_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное именование переменной &apos;{0}&apos;, она должна иметь один из следующих префиксов: &apos;is&apos;, &apos;has&apos;, &apos;can&apos;, &apos;do&apos;.
        /// </summary>
        public static string CREO009_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO009_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменная имеет неверный префикс.
        /// </summary>
        public static string CREO009_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO009_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс-атрибут должен содержать суффикс &apos;Attribute&apos;.
        /// </summary>
        public static string CREO010_AnalyzerDescriptionAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только классы-атрибуты должны содержать суффикс &apos;Attribute&apos;.
        /// </summary>
        public static string CREO010_AnalyzerDescriptionNonAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerDescriptionNonAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор класса-атрибута &apos;{0}&apos; должен содержать суффикс &apos;Attribute&apos;.
        /// </summary>
        public static string CREO010_AnalyzerMessageFormatAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerMessageFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индентификатор класса &apos;{0}&apos; не должен содержать суффикс &apos;Attribute&apos;, так как класс не является атрибутом.
        /// </summary>
        public static string CREO010_AnalyzerMessageFormatNonAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerMessageFormatNonAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор класса-атрибута не содержит суффикс &apos;Attribute&apos;.
        /// </summary>
        public static string CREO010_AnalyzerTitleAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerTitleAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс, не являющийся атрибутом, содержит суффикс &quot;Attribute&quot;.
        /// </summary>
        public static string CREO010_AnalyzerTitleNonAttribute {
            get {
                return ResourceManager.GetString("CREO010_AnalyzerTitleNonAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не используйте встроенный делегает Action для событий; Замените его на EventHandler.
        /// </summary>
        public static string CREO011_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO011_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие &apos;{0}&apos; использует делегат Action; Его необходимо заменить на EventHandler.
        /// </summary>
        public static string CREO011_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO011_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие использует недопустимый делегат.
        /// </summary>
        public static string CREO011_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO011_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор делегата для событий должен иметь суффикс EventHandler.
        /// </summary>
        public static string CREO012_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO012_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор  делегата &apos;{0}&apos;, используемого для объявления события, должен иметь суффикс EventHandler .
        /// </summary>
        public static string CREO012_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO012_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор делегата события имеет неправильный суффикс.
        /// </summary>
        public static string CREO012_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO012_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификаторы пространства имён и класса не должны быть одинаковыми.
        /// </summary>
        public static string CREO013_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO013_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарушение правила именования: У класса и пространства имён одинаковые идентификаторы (&apos;{0}&apos;).
        /// </summary>
        public static string CREO013_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO013_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У класса и пространства имён одинаковые идентификаторы.
        /// </summary>
        public static string CREO013_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO013_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пространства имён не должны быть вложенными.
        /// </summary>
        public static string CREO014_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO014_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пространство имён &apos;{0}&apos; является вложенным..
        /// </summary>
        public static string CREO014_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO014_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложенное пространство имён.
        /// </summary>
        public static string CREO014_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO014_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все не вложенные классы должны находиться в разных файлах..
        /// </summary>
        public static string CREO015_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO015_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классы должны быть в разных файлах.
        /// </summary>
        public static string CREO015_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO015_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Более одного класса в файле.
        /// </summary>
        public static string CREO015_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO015_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каждый элемент перечисления должен находиться на отдельной строке..
        /// </summary>
        public static string CREO016_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO016_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все элементы перечисления &apos;{0}&apos; находятся на разных строках..
        /// </summary>
        public static string CREO016_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO016_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все элементы перечисления находятся на отдельных строках..
        /// </summary>
        public static string CREO016_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO016_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нижнее подчёркивание не должно использоваться в качестве разделителя слов в идентификаторах.
        /// </summary>
        public static string CREO017_AnalyzerDescription {
            get {
                return ResourceManager.GetString("CREO017_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарушение правила именования: Идентификатор &apos;{0}&apos; содержит нижнее подчёркивание в качестве разделителя слов.
        /// </summary>
        public static string CREO017_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CREO017_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В идентфикаторах нельзя использовать нижнее подчёркивание для разделения слов..
        /// </summary>
        public static string CREO017_AnalyzerTitle {
            get {
                return ResourceManager.GetString("CREO017_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
